import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { DarkModeToggle } from "@/components/DarkModeToggle";
import FooterWithSnakeGame from "@/components/footer/FooterWithGame";
import { SpeedInsights } from "@vercel/speed-insights/next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <div className="flex flex-col min-h-screen bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100">
            <header className="p-4 flex justify-between items-center">
              <DarkModeToggle />
            </header>
            <main className="flex-grow">{children}</main>
            <FooterWithSnakeGame />
          </div>
          <SpeedInsights />
        </ThemeProvider>
      </body>
    </html>
  );
}
